### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by ryc16** [couchbaselabs/nativescript-couchbase#22]
Try to follow the step from http://blog.couchbase.com/2016/april/couchbase-mobile-in-a-cross-platform-telerik-nativescript-app.

Here is the exact step I did but got build failed. 
```
\> tns create demo-couchbase --tsc
\> cd demo-couchbase
\> tns plugin add nativescript-couchbase
\> tns platform add android
\> tns livesync android --watch

:config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-couchbase

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\demo-couchbase\platforms\android\build.gradle' line: 349

* What went wrong:
A problem occurred evaluating root project 'democouchbase'.
> String index out of range: -1

```
Here is my version

```
\>tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.1.0           │ 2.1.1          │ Update available │
│ tns-core-modules │ 2.1.0           │ 2.1.0          │ Up to date       │
│ tns-android      │ 2.1.1           │ 2.1.1          │ Up to date       │
│ tns-ios          │                 │ 2.1.1          │ Not installed    │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘
```

Any idea?

**Comment by nraboy** [comment]
I'm running through it now.  While I do this, can you try to run one of the demos that are packaged with the plugin?:

```
git clone https://github.com/couchbaselabs/nativescript-couchbase
cd nativescript-couchbase
npm install
npm run setup
npm run android-vanilla
```

To see what the `npm run` commands are doing, take a look at the **package.json** file.

I tested the demos the other day, but you never know something could have changed with NativeScript.  Would like to pin down the point of failure.

Best,

**Comment by ryc16** [comment]
@nraboy, thanks for your quick response. 

Just quickly try. after I did "npm run setup", I got different error shown below. Am I running different version of node.js or npm? If so, what version should I use?

```
>npm run setup

> nativescript-couchbase@1.0.8 setup C:\codeprojs\NativeScript\2plugins\nativescript-couchbase
> npm run setup-vanilla; npm run setup-angular

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup-vanilla;" "npm" "run" "setup-angular"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6

npm ERR! missing script: setup-vanilla;
```

Not sure about different error by creating new nativescript project. Would you be able to create new nativescript and add the plugin because need to know the exact step to add into existing project. 

By the way, when create a new database  
> var database = new couchbaseModule.Couchbase("test-database");

where is the physical location or file for "test-database" on the device? 
what kind of file type it would be, pain-text or binary?
what is the I/O performance comparing with nativescript application-settings which also save JSON text

Thanks

**Comment by nraboy** [comment]
Hey @ryc16,

There was actually a bug I had to squash.  For a reference, @NathanaelA wrote a post that I used to resolve the issue.  It was related to NativeScript 2.1.x and can be read about here:

http://fluentreports.com/blog/?p=167

In regards to the errors you received when trying to run the demos.  I didn't realize you were on Windows so I assume it is failing when it tries to build the iOS components.  That or there could be other issues with your development environment.

If using TypeScript, you wouldn't exactly be using this:

```
var database = new couchbaseModule.Couchbase("test-database");
```

You might want to look at both demos.  They both use TypeScript rather than vanilla JavaScript.  In regards to storage, the database resides in the protected partition of the device.  It cannot be accessed without rooting or jailbreaking the device.  It will be in a proprietary format.

Couchbase Lite will perform faster than application-settings when it comes to querying.  The application-settings module is only a key-value store, where as, Couchbase is a document database.  You cannot query a key-value store like you can a document database.  Direct lookups based on key will have equal performance for both Couchbase and application-settings.

I've confirmed that everything works now.  If you find another bug don't hesitate to open another issue ticket.  If you need general help, I encourage you to take it to the Couchbase forums:

https://forums.couchbase.com/

Best,
