### ISSUE TITLE
iOS Build Error on Telerik AppBuilder

### ISSUE THREAD

**Issue by spike1292** [couchbaselabs/nativescript-couchbase#34]
Getting the following error on the Telerik AppBuilder when trying to build a project.

```
Error: Cannot build project because module nativescript-couchbase contains insecure code. Remove the module and try again.
Error: 'Build failed with error code 2
```

looks like the same issue as https://github.com/bradmartin/nativescript-floatingactionbutton/issues/24

**Comment by nraboy** [comment]
Including @tjvantoll and @bradmartin on this thread.

TJ, do you just need to add this plugin to the verified list?  I don't use AppBuilder, so I don't have much information on it.

**Comment by bradmartin** [comment]
I've been through this with my plugins. 

App Builder wants all contributors to be 'verified' which has caused issues a lot (since plugins are open source :) ). Supposedly there will be a release to AppBuilder later this month that addresses this and the plugins should no longer throw this error in AppBuilder. I was pretty confused when someone first reported it but fingers crossed itll be in the past with next release.

**Comment by nraboy** [comment]
So should people sit tight for now?

This is isolated to AppBuilder, correct?  People who do not use AppBuilder should experience no issues, right?

**Comment by bradmartin** [comment]
Yes and yes. Only AppBuilder and shouldn't be an issue much longer.

**Comment by spike1292** [comment]
Thank you the responses. Also got feedback from telerik and they are confirming that the next release of appbuilder will fix this issue.
Until then i can't use appbuilder in our ci.
Back to "it works on my machine" builds..

**Comment by nraboy** [comment]
@spike1292,

It has been a few months so I'm following up with you.  Has Telerik corrected this problem for you?  Still not an AppBuilder user myself.

cc @bradmartin @tjvantoll

**Comment by nraboy** [comment]
Closing issue as I'm assuming Telerk / Progress resolved the problem.
