### ISSUE TITLE
Use in Worker

### ISSUE THREAD

**Issue by dave-calleja** [couchbaselabs/nativescript-couchbase#47]
Trying to use Couchbase in a worker as initialising DB with all the data stalls the apps for about 10 seconds.

Unfortunately in iOS (works in android) the apps shuts down when a new instance of the connection is created and createDocument is called.

> CONSOLE WARN file:///app/tns_modules/utils/utils.js:175:14: Objective-C class name "UIDocumentInteractionControllerDelegateImpl" is already in use - using "UIDocumentInteractionControllerDelegateImpl1" instead.
CONSOLE LOG file:///app/components/list/list.component.ts:35:24: azzopardi m miss
*** Assertion failure in -[CBL_FMDatabase beginUse], /Users/jenkins/jenkins/workspace/couchbase-lite-ios-builds/couchbase-lite-ios/vendor/fmdb/src/FMDatabase.m:967
Dec 22 16:27:00 davec-mbp-2 com.apple.CoreSimulator.SimDevice.3663BC7F-316F-440D-8EC2-D8AF816AB810.launchd_sim[28610] (UIKitApplication:org.nativescript.couchbasenativescript[0x9fd8][28807]): Service exited due to Segmentation fault: 11

**Comment by nraboy** [comment]
Hey @dave-calleja,

I'm pulling @tjvantoll and @triniwiz into this.  I think this is a NativeScript thing, maybe not a Couchbase thing.  @triniwiz added worker support for Android, but I didn't think iOS needed it.

Anyone have any input on this?

Thanks,

**Comment by triniwiz** [comment]
@nraboy iOS will crash if you try using cb in the worker what i did was pass the data from a map reduce but if you want more info on cb and threads check out https://developer.couchbase.com/documentation/mobile/current/guides/couchbase-lite/native-api/manager/index.html#concurrency-support

**Comment by nraboy** [comment]
Not sure I follow @triniwiz.  Are you saying that NativeScript workers can't be used on threaded native code in iOS?

I'm not sure I understand your solution either.  Can you be more specific?

**Comment by triniwiz** [comment]
@nraboy after i ran into the problem i took a look at the docs here are the main points 👇

* You can’t use any of the Couchbase Lite objects (databases, documents, models…) you were using on the main thread. Instead, you have to use the CBLDatabase object passed to the block, and the other objects reachable from it.
* You can’t save any of the Couchbase Lite objects in the block and then call them on the main thread. (For example, if in the block you allocated some CBLModels and assigned them to properties of application objects, bad stuff would happen if they got called later on by application code.)
* And of course, since the block is called on a background thread, any application or system APIs you call from it need to be thread-safe.

    My e.g

```js    
import * as platform from "platform";
// database.createView("things", "1", function(document, emitter) {
    emitter.emit(document._id, document);
});

//pass map reduce data into worker
if(platform.isIOS){ 
var rows = database.executeQuery("things");
var worker = new Worker('~/workers/thingWorker.js');
worker.onmessage = (msg)=>{
if(msg.data){
//the fanciness
}
};
worker.postMessage({items:rows,type:"idk"})
}


//thingWorker

onmessage =(msg)=>{
if(msg.data && msg.data.type === 'idk'){}
};

function doSomethingFancy(data){
postMessage(fancyData)
}
```

**Comment by nraboy** [comment]
Thanks @triniwiz.  Looks like I can close this ticket.  Please re-open otherwise.

Best,
